# Generated by Django 3.0.5 on 2020-04-29 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, null=True)),
                ('birthdate', models.DateField(default=datetime.date(2020, 4, 29))),
            ],
        ),
    ]
