# Generated by Django 3.0.6 on 2020-05-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
