# Generated by Django 3.0.6 on 2020-05-12 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('phone_number', models.CharField(default=380000000000, max_length=12, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='name of constraint teachers'),
        ),
    ]
