# Generated by Django 3.0.5 on 2020-05-04 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 14, 42, 51, 751541)),
        ),
    ]
