# Generated by Django 3.0.5 on 2020-05-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200504_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 14, 54, 44, 135922)),
        ),
    ]
