# Generated by Django 3.0.5 on 2020-05-04 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200504_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 4, 15, 1, 37, 674586)),
        ),
    ]
